fapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'fapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('addpost/', views.addpost, name='addpost'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('upvote/<str:pk>', views.up_vote, name='upvote'),
    path('downvote/<str:pk>/', views.down_vote, name='downvote'),
    path('comments/post/<str:pk>', views.comment, name='comments'),
    path('profile/<str:pk>', views.show_user_profile, name='profile'),
    path('edit_profile/<str:pk>', views.edit_profile, name="edit_profile"),
    path('delete_account/<str:pk>', views.delete_account, name="delete_account"),
    path('delete_foodie/<str:pk>', views.delete_post, name='delete_foodie'),
    path('delete_comment/<str:pk>', views.delete_comment, name='delete_comment')
]

foodie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fapp.urls')),
    path('', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    avatar = models.ImageField(null=True, default='avatar.svg')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self) -> str:
        return self.username

class Post(models.Model):
    body = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.body

class Comment(models.Model):
    body = models.TextField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.body

class UpVote(models.Model):
    voted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    voted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"User={self.voted_by} : Post = {self.post}"

class DownVote(models.Model):
    down_voted_by = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    down_voted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"User={self.down_voted_by} : Post = {self.post}"

fapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class PostForm(forms.Form):
    foodie = forms.CharField(label='',
                             max_length=200, 
                             widget=forms.Textarea(
                             attrs={'placeholder': 'Best meal to have today ?', 'rows': '4',
                                    'class':'input', 'style':'resize:none;'}))

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

class CommentForm(forms.Form):
    comment = forms.CharField(label='',
                               max_length=100,
                               widget=forms.Textarea(attrs={'placeholder': 'Add a comment',
                                                            'rows':'5',
                                                            'style':'resize:none;border-radius:8px;'}))

class ProfileForm(forms.ModelForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(required=True)
    
    class Meta:
        model = User
        fields = ['avatar','username', 'email', 'first_name', 'last_name']

fapp/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError
from django.utils.timezone import datetime
from django.db.models import Count

from django.views.decorators.csrf import csrf_protect


from fapp.helpers import get_side_bars_data

from .models import Comment, DownVote, Post, UpVote, User
from .forms import CommentForm, CustomUserCreationForm, PostForm, ProfileForm

import environ
import re


env = environ.Env()
 
environ.Env.read_env()

def home(request):

    q = request.GET.get('search') if request.GET.get('search') != None else ''

    posts = Post.objects.filter(body__icontains=q).order_by('-created_at')
    
    popular, recent = get_side_bars_data(request)

    form = PostForm
    
    context = {'posts': posts, 'form': form, 'popular': popular, 'recent': recent}

    return render(request, "fapp/index.html",context)

@login_required(login_url='/login')
def addpost(request):
    if request.method == 'POST':
        form = PostForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data['foodie']
            Post.objects.create(body=data, created_by=request.user)
            return redirect(reverse('fapp:home'))
        else:
            messages.error(request, "Fields are invalid")
            return redirect('fapp:home')

    return redirect(reverse('fapp:home'))

def login_user(request):
    
    if request.user.is_authenticated:
        return redirect(reverse('fapp:home'))

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            print(f"auth{email, password}")
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('fapp:home'))
            else:
                messages.error(request, "Invalid username or password")
                return redirect(reverse('fapp:login'))
        else:
            messages.error(request, "Invalid username or password")
            return redirect(reverse('fapp:login'))
    
    form = AuthenticationForm()

    context = {'form':form}

    return render(request, 'fapp/login.html', context)


@csrf_protect
def register(request):
 
    if request.user.is_authenticated:
        return redirect(reverse('fapp:home'))

    if request.method == 'POST':
        form  = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            message = 'Thank you for joining us. \n We are excited to have you'
            from_email = env('FROM_EMAIL')
            send_mail('Foodie App Registration', message, from_email, [request.POST['email']], fail_silently=True)
            return redirect(reverse('fapp:home'))
        messages.error(request, "\n".join([str(err) for err in form.error_messages.values()]))
        return redirect(reverse('fapp:register'))

    form = CustomUserCreationForm()
    
    context = {'form':form}

    return render(request, 'fapp/register.html', context)

def logout_user(request):
    logout(request)
    return redirect(reverse("fapp:home"))



def password_reset_request(request):
    if request.method == 'POST':
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "password/password_reset_email.txt"
                    c = {
                        "email":user.email,
                        'domain':'127.0.0.1:8000',
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    message = render_to_string(email_template_name, c)
                    from_email = env('FROM_EMAIL')
                    try:
                        send_mail(subject, message, from_email, [user.email], fail_silently=True)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found')
                    except Exception as e:
                        print("Error sending email", e)
                        messages.error(request, 'An error occurred')
                        return redirect(reverse('fapp:password_reset'))

                    return redirect(reverse('fapp:password_reset_done'))


    password_reset_form = PasswordResetForm()

    context={"password_reset_form":password_reset_form}

    return render(request, 'password/password_reset.html', context)

@login_required(login_url='/login')
def up_vote(request, pk):
    """
    If user has already voted - remove vote
    If user has not voted - add vote
    Remove user's down_vote when adding up_vote
    Can't have up vote and down_vote at same time
    """
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        messages.error(request, "Can't upvote for unknown post")
        return redirect(reverse("fapp:home"))
    
    up_vote = UpVote.objects.filter(Q(voted_by=request.user, post=post))
    if up_vote:
        up_vote.delete()
    else:
        down_vote = DownVote.objects.filter(Q(down_voted_by=request.user, post=post))
        if down_vote:
            down_vote.delete()
        UpVote.objects.create(post=post, voted_by=request.user)

    # Common code- found in down_vote(request,pk). Should be refactored
    referer = request.META['HTTP_REFERER']
    
    comment_search = re.search(r'/comments/post/', referer)
    
    if comment_search:
        return redirect(reverse('fapp:comments', kwargs={'pk': post.id }))
    
    profile_search = re.search(r'/profile/', referer)

    if profile_search:
        user_id = referer[-1:]
        return redirect(reverse('fapp:profile', kwargs={'pk':user_id}))

    return redirect(reverse("fapp:home") + f"#{post.id}")

@login_required(login_url='/login')
def down_vote(request, pk):
    """
    If user has already down voted - remove down_vote
    If user has not down voted - add down_vote
    Remove user's up_vote when adding down_vote
    Can't have up vote and down_vote at same time
    """
    try:
        post = Post.objects.get(pk=pk)
    except Post.DoesNotExist:
        messages.error(request, "Can't upvote for unknown post")
        return redirect(reverse("fapp:home"))
    
    down_vote = DownVote.objects.filter(Q(down_voted_by=request.user, post=post))
    if down_vote:
        down_vote.delete()
    else:
        up_vote = UpVote.objects.filter(Q(post=post, voted_by=request.user))
        if up_vote:
            up_vote.delete()
        DownVote.objects.create(post=post, down_voted_by=request.user)
    
    # Common code- found in up_vote(request,pk). Should be refactored
    referer = request.META['HTTP_REFERER']
    
    comment_search = re.search(r'/comments/post/', referer)
    
    if comment_search:
        return redirect(reverse('fapp:comments', kwargs={'pk': post.id }))
    
    profile_search = re.search(r'/profile/', referer)

    if profile_search:
        user_id = referer[-1:]
        return redirect(reverse('fapp:profile', kwargs={'pk':user_id}))
    
    return redirect(reverse('fapp:home') + f"#{post.id}")

@login_required(login_url='/login')
def comment(request, pk:str):
    
    post = Post.objects.filter(Q(pk=pk))
    if not post or len(post) == 0:
        messages.error(request, 'Post does not exist. No comments')
        return redirect(reverse('fapp:home'))

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['comment']
            Comment.objects.create(body=data, created_by=request.user, post=post[0])
            return redirect(reverse('fapp:comments', kwargs={'pk': pk}))
        else:
            messages.error(request, 'Invalid comment')
            return redirect(reverse('fapp:home'))
    
    popular, recent = get_side_bars_data(request)

    
    form = CommentForm()

    comments = Comment.objects.filter(Q(post=post[0])).order_by('-created_at')
    
    context = {'post': post, 'comments': comments, 'form': form, 'popular': popular, 'recent': recent}

    return render(request, 'fapp/comments.html', context)

def show_user_profile(request, pk):        

        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            messages.error(request, 'User unknown')
            return redirect(reverse('fapp:home'))
        
        posts = Post.objects.filter(Q(created_by=user))

        popular, recent = get_side_bars_data(request)

        context = {'user': user, 'posts': posts, 'popular': popular, 'recent':recent}
        
        return render(request, 'fapp/profile.html', context)
    
@login_required(login_url='login')
def edit_profile(request, pk):
    
    if request.method == 'POST':

fapp/templates/fapp/index.html
{% extends 'main.html' %} {% block main %} {% load static %}

<!--container-->
<section class="container">
  <!-- list of popular post-->
  {% include 'fapp/popular.html' %}
  <!-- end list of popular post-->

  <!--list of posts and form -->
  <section class="middle_col">
    <!--profile pic, form-->
    <section class="add_post">
      <div class="avatar1">
        {% if user.is_authenticated %}
        <img src="{{user.avatar.url}}" alt="" />
        {% else %}
        <img src="{% static '/images/avatar.svg' %}" alt="" />
        {% endif %}
      </div>
      <form method="post" action="{% url 'fapp:addpost' %}">
        {% csrf_token %} {{ form}}
        <input type="submit" value="Publish" />
      </form>
    </section>
    <!-- end of profile pic, form-->

    <!--list of posts -->
    <section class="list">
      {% if not posts %}
      <p>No posts available</p>
      {% endif %} {% for post in posts %}
      <div class="post" id="{{post.id}}">
        <div class="profile_pic">
          <img src="{{post.created_by.avatar.url}}" alt="" />
        </div>
        <div class="content">
          <p class="name">
            <strong>
              <a href="{% url 'fapp:profile' post.created_by.id %}"
                >@{{post.created_by}}</a
              >
            </strong>
            <small>{{post.created_at | timesince}} ago</small>
          </p>
          <p class="body">{{post.body | capfirst }}</p>
          <div class="actions">
            <a href="{% url 'fapp:upvote' post.id %}" title="Up vote">
              <img src="{% static 'images/upvote.png' %}" alt="up vote icon" />
              {{post.upvote_set.all.count}}
            </a>
            <a href="{% url 'fapp:downvote' post.id %}" title="Down vote">
              <img
                src="{% static 'images/icons8-thumbs-down-24.png' %}"
                alt="down vote icon"
              />
              {{post.downvote_set.all.count}}
            </a>
            <a href="{% url 'fapp:comments' post.id %}" title="Comments">
              <img
                src="{% static 'images/icons8-comments-26.png' %}"
                alt="comment icon"
              />

              {{post.comment_set.all.count}}
            </a>
            {% if user == post.created_by %}
            <a 
              href="{% url 'fapp:delete_foodie' post.id %}" 
              title="Delete"
              onclick="deleteObject(event, 'DELETE_FOODIE')"
              ><img src="{% static 'images/icons8-delete-48.png' %}"
            /></a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </section>
    <!--end of list of posts -->
  </section>
  <!-- end list of  posts-->

  <!-- Your recent foodies-->
  {% include 'fapp/recent.html' %}
  <!-- Your recent foodies-->
</section>
<!-- end of container-->

<style>
  .container {
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
    column-gap: 1rem;
    width: 80%;
    margin: 0 auto;
  }
  /* list of posts */
  .middle_col {
    display: flex;
    flex-direction: column;
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
  }
  .list {
    margin-top: 1rem;
    align-self: flex-start;
    width: 100%;
  }
  .post {
    display: flex;
    padding: 1rem 0.4em;
    width: 100%;
    border-radius: 8px;
    color: rgb(6, 7, 68);
    margin-bottom: 1rem;
    color: (66, 49, 49);
    transition: all 0.2s ease-in;
    border: 1px solid rgb(209, 200, 200);
    padding: 1rem;
    border-radius: 8px;
    cursor: default !important;
  }
  .post:hover {
    border: 1px solid rgb(122, 117, 117);
    cursor: pointer;
  }
  .post > .profile_pic {
    height: 2rem;
    width: 2rem;
    border-radius: 100%;
    margin-right: 0.3em;
  }
  .post > .profile_pic > img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    border: 1px solid hsl(0, 0%, 60%);
    border-radius: 100%;
  }
  .content > .name {
    margin-bottom: 0.4em;
  }
  .content > .name > strong {
    font-size: 1.1rem;
  }
  .content > .name > strong:hover {
    text-decoration: underline;
  }
  .content > .body {
    font-size: 1.1rem;
    white-space: pre;
  }
  .content p {
    margin: 0;
  }
  .content > .actions {
    display: flex;
    justify-content: space-between;
  }
  .content > .actions a {
    display: flex;
    align-items: center;
    margin-top: 1.2rem;
    margin-right: 1rem;
  }
  .content > .actions a > img {
    margin-right: 0.1rem;
    transition: background-color 0.5s ease-in;
    width: 20px;
    height: 20px;
  }
  .content > .actions a:hover {
    border-bottom: 1px solid black;
  }
  .add_post > .avatar1 {
    height: 2.7em;
    width: 2.9rem;
    margin-right: 0.3rem;
  }
  .add_post > .avatar1 > img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    border: 1px solid hsl(0, 0%, 60%);
    border-radius: 50%;
  }
  @media screen and (max-width: 1016px) {
    .container {
      grid-template-columns: 1fr 3fr;
      column-gap: 0.5rem;
      width: 95%;
    }
    .recent_main {
      display: none;
    }
  }
  @media screen and (max-width: 682px) {
    .container {
      grid-template-columns: 1fr;
      width: 100%;
      margin: 0 0.5rem;
    }
    .popular_main,
    .recent_main {
      display: none;
    }
    .middle_col {
      width: 85%;
    }
    .add_post {
      width: 70%;
      align-self: center;
      flex-direction: column;
    }
    .add_post > .avatar1 {
      margin-bottom: 1rem;
      width: 2.5em;
      height: 2.5rem;
    }
    .add_post > form {
      width: 100%;
    }
  }

  @media screen and (max-width: 400px) {
    .middle_col {
      width: 80%;
    }
    .add_post {
      width: 70%;
      align-self: center;
    }
  }
</style>
{% endblock %}

fapp/templates/fapp/popular.html
{% load static %}
<!-- list of popular post-->

<section class="popular_main">
  <h2>Popular Foodies</h2>

  {% if not popular %}
  <p>Nothing found</p>
  {% endif %}

  <section class="wrapper">
    {% for post in popular %}
    <section class="popular_post">
      <a href="{% url 'fapp:comments' post.id %}">
        <div class="profile">
          <div class="profile_pic">
            <img src="{{post.created_by.avatar.url}}" alt="" />
          </div>

          <strong> @{{post.created_by}}</strong>

          <small style="margin-top: 0.2rem"
            >&nbsp;{{post.created_at | timesince}} ago</small
          >
        </div>

        <div class="content">
          <p class="body" style="white-space: pre">{{post.body | capfirst }}</p>

          <div class="actions">
            <p>
              <img src="{% static 'images/upvote.png' %}" alt="up vote icon" />
              {{post.upvote_set.all.count}}
            </p>
            <p>
              <img
                src="{% static 'images/icons8-thumbs-down-24.png' %}"
                alt="down vote icon"
              />
              {{post.downvote_set.all.count}}
            </p>
            <p>
              <img
                src="{% static 'images/icons8-comments-26.png' %}"
                alt="down vote icon"
              />
              {{post.comment_set.all.count}}
            </p>
          </div>
        </div>
      </a>
    </section>

    {% endfor %}
  </section>
</section>

<!-- endlist of popular post-->

<style>
  .wrapper {
    border-radius: 8px;
    padding: 0.2rem;
    border: 1px solid hsl(0, 7%, 70%);
    border-radius: 8px;
  }
  .popular_post {
    display: flex;
    padding: 0.2rem;
    width: 100%;
    color: rgb(6, 7, 68);
    transition: all 0.2s ease-in;
    border-bottom: 1px solid hsl(0, 7%, 70%);
  }
  .popular_post:last-of-type {
    border-bottom: 0;
  }
  .popular_post:hover {
    background-color: hsl(0, 7%, 95%);
    cursor: pointer;
  }
  .popular_post .profile_pic {
    height: 1.6rem;
    width: 1.6rem;
    border-radius: 100%;
    margin-right: 0.3em;
  }
  .profile_pic > img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    border: 1px solid hsl(0, 0%, 60%);
    border-radius: 100%;
  }
  .content {
    margin-top: 0.5rem;
  }
  .content > .actions {
    display: flex;
    justify-content: space-between;
  }
  .content > .actions p {
    display: flex;
    align-items: center;
    margin-top: 1.2rem;
  }
  .content > .actions p > img {
    margin-right: 0.1rem;
    transition: background-color 0.5s ease-in;
    width: 20px;
    height: 20px;
  }
  .popular_post > a {
    display: block;
    width: 100%;
    padding: 0.7em;
  }

  .profile {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
  }
</style>

fapp/templates/fapp/profile.html
{% extends 'main.html' %} {% block main %} {% load static %}
<section class="container">
  <!-- list of popular post-->
  {% include 'fapp/popular.html' %}
  <!-- end list of popular post-->

  <!--middle-->
  <section class="middle">
    <!-- user details -->
    <section class="user_info">
      <img src="{{user.avatar.url}}" alt="user profile picture" />
      <section class="bio">
        <p><span class="bold">Username:</span> {{user.username | title }}</p>
        {% if user.first_name %}
        <p>
          <span class="bold">First name:</span> {{user.first_name | title }}
        </p>
        {% else %}
        <p><span class="bold">First name:</span> unkown</p>
        {% endif %} {% if user.last_name %}
        <p><span class="bold">Last name:</span> {{user.last_name | title}}</p>
        {% else %}
        <p><span class="bold">Last name:</span> unkown</p>
        {% endif %}
        <p><span class="bold">Email:</span> {{user.email}}</p>
      </section>
    </section>
    <!-- end user details -->

    <!-- Posts by user -->
    <section>
      <h2>Foodies by {{user}}</h2>

      {% if not posts %}
      <p>{{user | capfirst }} has not created a foodie since they joined</p>
      {% endif %} {% for post in posts %}
      <div id="{{post.id}}" class="foodies">
        <section class="foodie_content">
          <div id="{{post.id}}" style="white-space: pre">
            <strong>{{post.body | capfirst}}</strong>
          </div>
          <small>{{post.created_at | timesince}}</small>
          <div class="foodie_actions">
            <a href="{% url 'fapp:upvote' post.id %}" title="Up vote">
              <img src="{% static 'images/upvote.png' %}" alt="up vote icon" />
              {{post.upvote_set.all.count}}
            </a>
            <a href="{% url 'fapp:downvote' post.id %}" title="Down vote">
              <img
                src="{% static 'images/icons8-thumbs-down-24.png' %}"
                alt="down_vote_icon"
              />
              {{post.downvote_set.all.count}}
            </a>
            <a href="{% url 'fapp:comments' post.id %}" title="Comments">
              <img
                src="{% static 'images/icons8-comments-26.png' %}"
                alt="down_vote_icon"
              />

              {{post.comment_set.all.count}}
            </a>
          </div>
        </section>
      </div>

      {% endfor %}
    </section>
    <!-- End of posts by user -->

    <!-- Security -->
    <section class="security">
      {% if user == request.user %}
      <a href="{% url 'fapp:edit_profile' user.id %}"> Edit profile </a>
      <br />
      <a
        href="{% url 'fapp:delete_account' user.id %}"
        onclick="deleteObject(event, 'DELETE_ACCOUNT')"
      >
        Delete account
      </a>
      {% endif %}
    </section>
    <!-- end of security -->
  </section>
  <!--end of middle -->

  <!-- Your recent foodies-->
  {% include 'fapp/recent.html' %}
  <!-- Your recent foodies-->
</section>

<style>
  .container {
    display: grid;
    grid-template-columns: 1fr 3fr 1fr;
    column-gap: 1rem;
    width: 80%;
    margin: 0 auto;
  }
  .middle {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
  }
  .user_info {
    display: flex;
    flex-direction: column;
    border-radius: 8px;
    padding-top: 1rem;
  }
  .user_info > img {
    height: 6rem;
    width: 6rem;
    align-self: center;
    justify-self: center;
    border-radius: 50%;
    border: 1px solid hsl(0, 0%, 60%);
  }
  .user_info > .bio {
    padding: 1rem;
  }
  .foodies {
    border: 1px solid grey;
    margin-bottom: 1rem;
    padding: 1rem;
    border-radius: 8px;
  }
  .foodie_content > .foodie_actions {
    margin-top: 1rem;
    display: flex;
    justify-content: space-between;
  }
  .security {
    display: flex;
    margin-bottom: 1rem;
    justify-content: space-between;
  }
  .security > a {
    border: 1px solid grey;
    padding: 0.5rem;
    border-radius: 8px;
  }
  .security > a:last-of-type {
    border: 1px solid red;
  }
  @media screen and (max-width: 1016px) {
    .container {
      grid-template-columns: 1fr 3fr;
      column-gap: 0.5rem;
      width: 95%;
    }
    .recent_main {
      display: none;
    }
    .bold {
      font-weight: 700;
    }
  }
  @media screen and (max-width: 682px) {
    .container {
      grid-template-columns: 1fr;
      width: 100%;
      margin: 0 0.5rem;
    }
    .popular_main,
    .recent_main {
      display: none;
    }
    .middle_col {
      width: 85%;
    }
    .add_post {
      width: 85%;
      align-self: center;
    }
    .foodies,
    .security {
      width: 95%;
    }
  }
</style>

{% endblock main %}