fapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'fapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('addpost/', views.addpost, name='addpost'),
    path('login/', views.login_user, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="password/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('upvote/<str:pk>', views.up_vote, name='upvote'),
    path('downvote/<str:pk>/', views.down_vote, name='downvote'),
    path('comments/post/<str:pk>', views.comment, name='comments'),
    path('profile/<str:pk>', views.show_user_profile, name='profile'),
    path('edit_profile/<str:pk>', views.edit_profile, name="edit_profile"),
    path('delete_account/<str:pk>', views.delete_account, name="delete_account"),
    path('delete_foodie/<str:pk>', views.delete_post, name='delete_foodie'),
    path('delete_comment/<str:pk>', views.delete_comment, name='delete_comment')
]

foodie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fapp.urls')),
    path('', include('django.contrib.auth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/footer.html
<style>
  footer {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    border-top: 1px solid hsl(0, 2%, 80%);
    margin-top: 1rem;
    padding: 1.5rem 0;
    position: relative;
    bottom: -200px;
    height: 100%;
    margin-bottom: 0;
  }
</style>
<footer>&copy; 2RMeP {% now "Y" %}</footer>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/navbar.css' %}"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/middle_column.css' %}?v=22"
    />
    <script defer src="{% static 'js/app.js' %}"></script>
    <title>2RMeP</title>
    <style>
      .app_container {
        display: flex;
        flex-direction: column;
      }

      .main_content {
        margin-top: 3rem;
      }

      .message {
        text-align: center;
        padding: 1rem;
        background: rgb(238, 234, 230);
        width: 40%;
        margin: 0 auto;
        margin-bottom: 1rem;
        border-radius: 8px;
      }
    </style>
  </head>

  <body style="user-select: none">
    <div class="app_container">
      {% include 'navbar.html' %}
      <main class="main_content">
        {% if messages %} {% for message in messages %}
        <p class="message">{{ message }}</p>
        {% endfor %} {% endif %} {% block main %} {% endblock main%}
      </main>
      {% include 'footer.html' %}
    </div>
  </body>
</html>

templates/navbar.html
<style>
  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    border-bottom: 1px solid hsl(0, 3%, 80%);
    padding: 0.5rem 1rem;
    width: 100%;
  }

  .search {
    border-radius: 5px;
    padding: 0.5rem;
    border: 1px solid grey;
    text-align: center;
    width: 100%;
  }

  .search:focus {
    /* border:  1px solid hsl(0, 0%, 40%); */
    outline: hsl(0, 0%, 50%) solid 1px;
  }

  .avatar {
    height: 2rem;
    width: 2rem;
    border-radius: 50%;
    display: grid;
    place-items: center;
    margin-right: 0.5rem;
  }

  .avatar > img {
    width: 100%;
    height: 100%;
    object-fit: contain;
    border: 1px solid hsl(0, 0%, 60%);
    border-radius: 50%;
  }

  .dropdown,
  p {
    margin: 0;
    padding: 0;
    position: relative;
  }

  .dropdown_visible {
    display: flex;
    align-items: center;
  }

  .dropdown_toggle {
    position: absolute;
    border: 1px solid hsl(0, 19%, 88%);
    border-radius: 8px;
    padding: 1rem 0;
    margin-top: 0.1rem;
    width: 85px;
    background-color: hsl(0, 19%, 99%);
    display: none;
  }

  .dropdown_toggle > a {
    display: block;
    text-align: center;
    padding: 0.2rem 0;
    margin-bottom: 0.2rem;
  }

  .dropdown_toggle > a:hover {
    background-color: hsl(0, 19%, 88%);
  }

  .dropdown:active > .dropdown_toggle,
  .dropdown:hover > .dropdown_toggle {
    display: block;
  }

  @media screen and (max-width: 400px) {
    .search_input {
      display: none;
    }
  }
</style>

<nav class="navbar">
  <!--Logo-->
  <a href="{% url 'fapp:home' %}" class="logo">
    {% comment %} <div class="logo_text_1">F</div> {% endcomment %}
    <p class="logo_text_2">2RMeP</p>
  </a>

  <!--Search field-->
  <form action="{% url 'fapp:home' %}" method="get" class="search_input">
    <input placeholder="Find a foodie" name="search" class="search" />
  </form>

  <!--Signin, sign out-->
  <ul class="links">
    {% if not user.is_authenticated %}
    <li><a href="{% url 'fapp:login' %}">Login</a></li>
    <li><a href="{% url 'fapp:register' %}">Register</a></li>
    {% else %}

    <li class="dropdown">
      <div class="dropdown_visible">
        <div class="avatar">
          <img src="{{user.avatar.url}}" alt="" />
        </div>
        <p>{{user.username | capfirst }}</p>
      </div>
      <div class="dropdown_toggle">
        <a href="{% url 'fapp:home' %}">Home</a>
        <a href="{% url 'fapp:profile' user.id %}">Profile</a>
        <a href="{% url 'fapp:logout' %}">Logout</a>
      </div>
    </li>

    {% endif %}
  </ul>
</nav>